# Generated by Django 3.1.4 on 2021-01-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
